// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AuthRequestProto.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	AuthRequestProto.proto
	FrameProto.proto
	GameStartResponseProto.proto
	InputDataProto.proto
	PullRequestProto.proto
	PullResponseProto.proto
	ResponseProto.proto
	SyncRequestProto.proto

It has these top-level messages:
	AuthRequest
	Frame
	GameStartResponse
	PlayerInfo
	InputData
	PullRequest
	PullResponse
	Response
	SyncRequest
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	RoundId string `protobuf:"bytes,1,opt,name=roundId" json:"roundId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	Sid     string `protobuf:"bytes,3,opt,name=sid" json:"sid,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetRoundId() string {
	if m != nil {
		return m.RoundId
	}
	return ""
}

func (m *AuthRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
}

func init() { proto.RegisterFile("AuthRequestProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x73, 0x2c, 0x2d, 0xc9,
	0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00, 0x91,
	0x4a, 0x81, 0x5c, 0xdc, 0x48, 0x32, 0x42, 0x12, 0x5c, 0xec, 0x45, 0xf9, 0xa5, 0x79, 0x29, 0x9e,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x18, 0x17, 0x5b, 0x69, 0x71,
	0x6a, 0x91, 0x67, 0x8a, 0x04, 0x13, 0x58, 0x02, 0xca, 0x13, 0x12, 0xe0, 0x62, 0x2e, 0xce, 0x4c,
	0x91, 0x60, 0x06, 0x0b, 0x82, 0x98, 0x4e, 0x26, 0x5c, 0x1a, 0xc9, 0xf9, 0xb9, 0x7a, 0x99, 0xb9,
	0xb9, 0xf9, 0xb9, 0xf9, 0x7a, 0x55, 0xf9, 0xb9, 0x49, 0x99, 0xa9, 0x05, 0x89, 0x45, 0x25, 0x95,
	0x7a, 0xe9, 0x89, 0xb9, 0xa9, 0xc5, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0x10, 0xdb, 0x8b, 0x03, 0x18,
	0xa3, 0xd8, 0x20, 0xac, 0x24, 0x08, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x15, 0xf2,
	0x05, 0xa9, 0x00, 0x00, 0x00,
}
